# Dynamic configuration
http:
  middlewares:
    user-auth:
      basicAuth:
        users:
          - "user:$apr1$tr4xmavg$BVDfOg1qtWtd8L34VPBih/"

  middlewares-https-redirect:
    redirectScheme:
      scheme: https
      permanent: true
      port: 443   