version: '3.3'
########################### NETWORKS
# Create proxy network
# $ docker network create proxy
networks:
  proxy:
    external: true
services:
####Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy
  traefik:
    image: traefik:$TRAEFIKVERSION
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Add folder with STATIC configuration yml
      - ./traefik_config/traefik.yml:/traefik.yml:ro
      - ./traefik_config/log/access.log:/log/access.log
      - ./traefik_config/acme/acme.json:/acme.json
      # Add folder with dynamic configuration yml
      - ./traefik_config/configurations:/configurations
    networks:
      - proxy
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.traefik-https-rtr.entrypoints=https
      - traefik.http.routers.traefik-https-rtr.rule=Host(`traefik.$DOMAINNAME`)
      ## Middlewares Rules
      - traefik.http.routers.traefik-https-rtr.middlewares=user-auth@file
      ## Service Rules
      - traefik.http.routers.traefik-https-rtr.service=api@internal
####Portainer is a lightweight management UI which allows you to easily manage your different Docker
  portainer:
    container_name: portainer
    image: portainer/portainer:$PORTAINERVERSION
    restart: always
    depends_on:
      - traefik
    command: -H unix:///var/run/docker.sock
    expose:
      - 9000
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.portainer-http-rtr.rule=Host(`portainer.$DOMAINNAME`)
      - traefik.http.routers.portainer-http-rtr.entrypoints=http
      - traefik.http.routers.portainer-https-rtr.rule=Host(`portainer.$DOMAINNAME`)
      - traefik.http.routers.portainer-https-rtr.entrypoints=https
      - traefik.http.routers.portainer-https-rtr.tls=true
      - traefik.http.routers.portainer-https-rtr.tls.certresolver=letsencrypt
      ## Middlewares Rules
      - traefik.http.routers.portainer-http-rtr.middlewares=middlewares-https-redirect@file
####whoami test in front page
  whoami:
    container_name: frontpage
    image: containous/whoami
    restart: always
    depends_on:
      - traefik
    expose:
      - 80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.whoami-http-rtr.rule=Host(`$DOMAINNAME`)
      - traefik.http.routers.whoami-http-rtr.entrypoints=http
      - traefik.http.routers.whoami-https-rtr.rule=Host(`$DOMAINNAME`)
      - traefik.http.routers.whoami-https-rtr.entrypoints=https
      - traefik.http.routers.whoami-https-rtr.tls=true
      - traefik.http.routers.whoami-https-rtr.tls.certresolver=letsencrypt
      ## Middlewares Rules
      - traefik.http.routers.whoami-http-rtr.middlewares=middlewares-https-redirect@file